# Generated by Django 5.0.6 on 2024-09-09 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('question_type', models.CharField(choices=[('Text', 'Text'), ('Bigtext', 'Bigtext'), ('Redio', 'Redio'), ('Checkbox', 'Checkbox')], default='Text', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_name', models.CharField(max_length=100)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='rate.questions')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_text', models.TextField(blank=True, null=True)),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rate.customerfeedback')),
                ('selected_options', models.ManyToManyField(blank=True, to='rate.options')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rate.questions')),
            ],
        ),
        migrations.AddField(
            model_name='customerfeedback',
            name='question',
            field=models.ManyToManyField(to='rate.questions'),
        ),
    ]
